name: Synchronize Submodule
on: workflow_dispatch
  # schedule:
  #   - cron: "0 0 * * *"

jobs:
  sync-submodule:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    # if: github.event.pull_request.draft == false && github.base_ref == 'main' && github.event.pull_request.base.repo.full_name == 'hpcaitech/ColossalAI'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Git Sumbodule Update
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive

      - name: Commit update
        run: |
          git config --global user.name 'Git bot'
          git config --global user.email 'bot@noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "Auto updated submodule references" && git push || echo "No changes to commit"
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: '[Bot] Synchronize Submodule References'
          body: |
            Automated PR to update submodule commits
          committer: GitHub <noreply@github.com>
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          assignees: ${{ github.actor }}
          branch: create-pull-request/patch-sync-submodule
          delete-branch: true
          # reviewers: hpcaitech/pull-request-reviewer